name = "ai-xbot-backend"
compatibility_date = "2025-12-10"
main = "server.js"

account_id = "$CLOUDFLARE_ACCOUNT_ID"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "ai-xbot-db"
database_id = "$D1_DATABASE_ID"