name = "aixbot-worker"
compatibility_date = "2025-12-10"
main = "server.js"

account_id = "9b465668c4d3a03532bc68088cdf3909"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "aixbot-db"
database_id = "c0937697-dc3c-4af5-9486-25ac3961ab5b"  # 请替换为实际的D1数据库ID